spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/BurundiRoots
    username: Rumata76
    password: dedansCNJ1!
    driver-class-name: org.postgresql.driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    freemaker:
      expose-session-attributes: true

server:
  port: 8080